// Copyright 2016 - 2026 The excelize Authors. All rights reserved. Use of
// this source code is governed by a BSD-style license that can be found in
// the LICENSE file.
//
// Package excelize providing a set of functions that allow you to write to and
// read from XLAM / XLSM / XLSX / XLTM / XLTX files. Supports reading and
// writing spreadsheet documents generated by Microsoft Excel™ 2007 and later.
// Supports complex components by high compatibility, and provided streaming
// API for generating or reading data from a worksheet with huge amounts of
// data. This library needs Go version 1.25.0 or later.

package excelize

import (
	"bytes"
	"io"
	"strings"
)

// SetPivotTableStyle applies a cell style to a fixed cell range in a pivot
// table. The styleID should be created with NewStyle. The rangeRef can be a
// cell, a cell range, a column, or a column range. For example, H, H:J, H5, or
// H5:J10.
// Column references are limited to the rows in the pivot table. The range must
// be contained in the pivot table range.
//
// The style is applied directly to the currently materialized pivot table
// cells and is also stored as an always-true conditional formatting rule marked
// for pivot table cells. The direct style makes the current result immediately
// visible, while the conditional format lets spreadsheet applications reapply
// supported differential-format properties after a pivot table refresh. The
// properties that can't be represented by differential formatting apply only
// to the currently materialized cells. The fixed range doesn't follow pivot
// field layout changes or growth beyond the range. Repeated calls for the same
// range replace the previous rule. The most recent call has precedence where
// ranges overlap. This function is concurrency safe.
func (f *File) SetPivotTableStyle(sheet, name, rangeRef string, styleID int) error {
	pivotTable, err := f.getPivotTableByName(sheet, name)
	if err != nil {
		return err
	}
	rangeRef, coordinates, err := getPivotTableStyleRange(sheet, rangeRef, pivotTable.Location)
	if err != nil {
		return err
	}
	style, err := f.GetStyle(styleID)
	if err != nil {
		return err
	}
	f.mu.Lock()
	ws, err := f.workSheetReader(sheet)
	if err != nil {
		f.mu.Unlock()
		return err
	}
	s, err := f.stylesReader()
	f.mu.Unlock()
	if err != nil {
		return err
	}
	ws.mu.Lock()
	defer ws.mu.Unlock()
	if err = walkMaterializedPivotTableCells(ws, coordinates, nil); err != nil {
		return err
	}
	s.mu.Lock()
	dxfID, err := f.newConditionalStyle(s, style, true)
	s.mu.Unlock()
	if err != nil {
		return err
	}
	removePivotTableStyleConditionalFormats(ws, rangeRef)
	normalizeConditionalFormatPriorities(ws, 2)
	ws.ConditionalFormatting = append(ws.ConditionalFormatting, &xlsxConditionalFormatting{
		Pivot: true,
		SQRef: rangeRef,
		CfRule: []*xlsxCfRule{{
			Type:     "expression",
			DxfID:    intPtr(dxfID),
			Priority: 1,
			Formula:  []string{"1"},
		}},
	})
	// Cell references were validated while holding the same worksheet lock, so
	// this second pass can't fail unless the worksheet changes concurrently.
	return walkMaterializedPivotTableCells(ws, coordinates, func(cell *xlsxC) {
		cell.S = styleID
	})
}

// walkMaterializedPivotTableCells calls the given function for cells already
// present in the worksheet XML. It avoids filling unused rows in an oversized
// PivotTableRange while still allowing an immediately visible normal cell
// style. A nil function validates the cell references without changing them.
func walkMaterializedPivotTableCells(ws *xlsxWorksheet, coordinates []int, fn func(*xlsxC)) error {
	for rowIndex := range ws.SheetData.Row {
		row := &ws.SheetData.Row[rowIndex]
		rowNumber := row.R
		if rowNumber == 0 {
			rowNumber = rowIndex + 1
		}
		if rowNumber < coordinates[1] || rowNumber > coordinates[3] {
			continue
		}
		for cellIndex := range row.C {
			cell := &row.C[cellIndex]
			columnNumber, cellRowNumber := cellIndex+1, rowNumber
			if cell.R != "" {
				var err error
				columnNumber, cellRowNumber, err = CellNameToCoordinates(cell.R)
				if err != nil {
					return err
				}
			}
			if columnNumber >= coordinates[0] && columnNumber <= coordinates[2] &&
				cellRowNumber >= coordinates[1] && cellRowNumber <= coordinates[3] {
				if fn != nil {
					fn(cell)
				}
			}
		}
	}
	return nil
}

// removePivotTableStyleConditionalFormats removes rules previously created for
// the same fixed range, so SetPivotTableStyle has replacement semantics.
func removePivotTableStyleConditionalFormats(ws *xlsxWorksheet, rangeRef string) {
	conditionalFormatting := ws.ConditionalFormatting[:0]
	for _, format := range ws.ConditionalFormatting {
		if isPivotTableStyleConditionalFormat(format, rangeRef) {
			continue
		}
		conditionalFormatting = append(conditionalFormatting, format)
	}
	clear(ws.ConditionalFormatting[len(conditionalFormatting):])
	ws.ConditionalFormatting = conditionalFormatting
}

// isPivotTableStyleConditionalFormat reports whether a conditional format is
// an always-true fixed-range rule created by SetPivotTableStyle.
func isPivotTableStyleConditionalFormat(format *xlsxConditionalFormatting, rangeRef string) bool {
	if format == nil || !format.Pivot || format.SQRef != rangeRef || len(format.CfRule) != 1 {
		return false
	}
	rule := format.CfRule[0]
	return rule != nil && rule.Type == "expression" && rule.DxfID != nil &&
		len(rule.Formula) == 1 && rule.Formula[0] == "1"
}

// getPivotTableByName returns a pivot table definition without reading its
// cache. This keeps SetPivotTableStyle available for every cache source type.
func (f *File) getPivotTableByName(sheet, name string) (*xlsxPivotTableDefinition, error) {
	if name == "" {
		return nil, ErrParameterRequired
	}
	if err := checkSheetName(sheet); err != nil {
		return nil, err
	}
	f.mu.Lock()
	sheetXML, ok := f.getSheetXMLPath(sheet)
	if !ok {
		f.mu.Unlock()
		return nil, ErrSheetNotExist{sheet}
	}
	rels := "xl/worksheets/_rels/" + strings.TrimPrefix(sheetXML, "xl/worksheets/") + ".rels"
	sheetRels, err := f.relsReader(rels)
	f.mu.Unlock()
	if err != nil {
		return nil, err
	}
	if sheetRels == nil {
		return nil, newNoExistTableError(name)
	}
	sheetRels.mu.Lock()
	defer sheetRels.mu.Unlock()
	for _, rel := range sheetRels.Relationships {
		if rel.Type != SourceRelationshipPivotTable {
			continue
		}
		pivotTableXML := strings.TrimPrefix(strings.ReplaceAll(rel.Target, "..", "xl"), "/")
		part, ok := f.Pkg.Load(pivotTableXML)
		if !ok || part == nil {
			continue
		}
		content, ok := part.([]byte)
		if !ok {
			continue
		}
		pivotTable := new(xlsxPivotTableDefinition)
		decoded := namespaceStrictToTransitional(append([]byte(nil), content...))
		if err = f.xmlNewDecoder(bytes.NewReader(decoded)).Decode(pivotTable); err != nil && err != io.EOF {
			return nil, err
		}
		if pivotTable.Name == name {
			return pivotTable, nil
		}
	}
	return nil, newNoExistTableError(name)
}

// getPivotTableStyleRange validates a worksheet range and returns the absolute
// worksheet reference used by pivot-aware conditional formatting.
func getPivotTableStyleRange(sheet, rangeRef string, location *xlsxLocation) (string, []int, error) {
	if rangeRef == "" {
		return "", nil, newPivotTableStyleRangeError(ErrParameterRequired.Error())
	}
	if location == nil || location.Ref == "" {
		return "", nil, newPivotTableStyleRangeError(ErrParameterInvalid.Error())
	}
	pivotCoordinates, err := rangeRefToCoordinates(location.Ref)
	if err != nil {
		return "", nil, newPivotTableStyleRangeError(err.Error())
	}
	_ = sortCoordinates(pivotCoordinates)

	ref := strings.TrimSpace(rangeRef)
	if idx := strings.LastIndex(ref, "!"); idx != -1 {
		rangeSheet := strings.TrimSpace(ref[:idx])
		if len(rangeSheet) >= 2 && rangeSheet[0] == '\'' && rangeSheet[len(rangeSheet)-1] == '\'' {
			rangeSheet = strings.ReplaceAll(rangeSheet[1:len(rangeSheet)-1], "''", "'")
		}
		if !strings.EqualFold(rangeSheet, sheet) {
			return "", nil, newPivotTableStyleRangeError("worksheet does not match " + sheet)
		}
		ref = strings.TrimSpace(ref[idx+1:])
	}
	targetCoordinates, err := getPivotTableStyleCoordinates(ref, pivotCoordinates)
	if err != nil {
		return "", nil, newPivotTableStyleRangeError(err.Error())
	}
	if targetCoordinates[0] < pivotCoordinates[0] || targetCoordinates[1] < pivotCoordinates[1] ||
		targetCoordinates[2] > pivotCoordinates[2] || targetCoordinates[3] > pivotCoordinates[3] {
		return "", nil, newPivotTableStyleRangeError("range must be within pivot table range " + location.Ref)
	}
	if targetCoordinates[0] == targetCoordinates[2] && targetCoordinates[1] == targetCoordinates[3] {
		cell, err := CoordinatesToCellName(targetCoordinates[0], targetCoordinates[1])
		if err != nil {
			return "", nil, newPivotTableStyleRangeError(err.Error())
		}
		return cell, targetCoordinates, nil
	}
	normalizedRange, err := coordinatesToRangeRef(targetCoordinates)
	if err != nil {
		return "", nil, newPivotTableStyleRangeError(err.Error())
	}
	return normalizedRange, targetCoordinates, nil
}

// getPivotTableStyleCoordinates parses cell and column range forms. A column
// range is expanded to the row bounds of the pivot table.
func getPivotTableStyleCoordinates(ref string, pivotCoordinates []int) ([]int, error) {
	ref = strings.ReplaceAll(strings.TrimSpace(ref), "$", "")
	parts := strings.Split(ref, ":")
	if len(parts) == 0 || len(parts) > 2 {
		return nil, ErrParameterInvalid
	}
	columnCoordinates := make([]int, len(parts))
	columnsOnly := true
	for idx, part := range parts {
		columnCoordinates[idx], _ = ColumnNameToNumber(part)
		if columnCoordinates[idx] < 1 {
			columnsOnly = false
			break
		}
	}
	if columnsOnly {
		if len(columnCoordinates) == 1 {
			columnCoordinates = append(columnCoordinates, columnCoordinates[0])
		}
		coordinates := []int{columnCoordinates[0], pivotCoordinates[1], columnCoordinates[1], pivotCoordinates[3]}
		_ = sortCoordinates(coordinates)
		return coordinates, nil
	}
	if len(parts) == 1 {
		col, row, err := CellNameToCoordinates(parts[0])
		if err != nil {
			return nil, err
		}
		return []int{col, row, col, row}, nil
	}
	coordinates, err := cellRefsToCoordinates(parts[0], parts[1])
	if err != nil {
		return nil, err
	}
	_ = sortCoordinates(coordinates)
	return coordinates, nil
}
